const { Router } = require('express')
const { signup, login, getMe, getCities } = require('../controllers/authController')
const { agent, exportExcel } = require('../controllers/agentController')
const { handleStudentRequest, getStudents, getStudentById, updateStudent } = require('../controllers/studentController')
const { getDashboardData, getDashboardMetrics, clearDashboardCache } = require('../controllers/dashboardController')
const { getSubjects, getGrades, getStudentsByGrade, markAttendance, getAttendance } = require('../controllers/attendanceController')

const router = Router()

router.post('/agent', agent)
router.post('/auth/signup', signup)
router.post('/auth/login', login)
router.get('/auth/me', getMe)
router.get('/auth/cities', getCities)
router.post('/export', exportExcel)
router.post('/students', handleStudentRequest)
router.get('/students', getStudents)
router.get('/students/:id', getStudentById)
router.put('/students/:id', updateStudent)
router.get('/dashboard', getDashboardData)
router.post('/dashboard/metrics', getDashboardMetrics)
router.delete('/dashboard/cache', clearDashboardCache)
router.get('/subjects', getSubjects)
router.get('/attendance/grades', getGrades)
router.get('/attendance/students', getStudentsByGrade)
router.post('/attendance', markAttendance)
router.get('/attendance', getAttendance)

module.exports = router
